package com.gtera.ui.utils

enum class AppScreenRoute {
    SPLASH_SCREEN,
    SIGN_IN_SCREEN,
    OTP_SCREEN,
    PRODUCT_DETAILS_SCREEN,
    MAIN_SCREEN,
    CART_SCREEN,
    SIGN_IN_SUCCESS,
    SEARCH_VIEW,
    CHANGE_LANGUAGE,
    PAYMENT_ONLINE_SUCCESS,
    PAYMENT_ONLINE_FAIL,

}